package nl.voidgroup.gradle.plugin.opengmph.task;

import groovy.lang.Closure;
import nl.voidgroup.gradle.plugin.opengmph.OpenGMPH;
import nl.voidgroup.gradle.plugin.opengmph.PluginHelperData;
import nl.voidgroup.gradle.plugin.opengmph.annotation.SupportsYMLGen;
import nl.voidgroup.gradle.plugin.opengmph.data.YMLObject;
import nl.voidgroup.gradle.plugin.opengmph.server.MinecraftServer;
import org.gradle.api.DefaultTask;
import org.gradle.api.tasks.TaskAction;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class GenPluginYML extends DefaultTask {

    public static final String header = "Plugin YML Generated By: <" + OpenGMPH.pluginName + "@" + OpenGMPH.pluginVersion + ">";

    @TaskAction
    public void run() throws IOException {
        PluginHelperData pluginHelperData = getProject().getExtensions().getByType(PluginHelperData.class);
        MinecraftServer targetServer = pluginHelperData.targetServer;
        if(!targetServer.getClass().isAnnotationPresent(SupportsYMLGen.class)) {
            getLogger().warn("Current target server does not support plugin yml gen");
            return;
        }
        String fileName = targetServer.getClass().getAnnotation(SupportsYMLGen.class).fileName();
        File pluginYML = new File(getProject().getBuildDir().getAbsolutePath() + "/resources/" + fileName);
        if(pluginYML.getParentFile().mkdirs()) {
            getLogger().info("Created parent dirs for: '" + pluginYML.getAbsolutePath() + "'");
        }
        if(pluginYML.createNewFile()) {
            getLogger().info("Created: '" + pluginYML.getAbsolutePath() + "'");
        }
        if(pluginHelperData.pluginData != null && targetServer.getPluginDataContainer() != null) {
            pluginHelperData.pluginData.setDelegate(targetServer.getPluginDataContainer());
            pluginHelperData.pluginData.call();
        }
        YMLObject out = targetServer.generatePluginYML(getProject(), pluginHelperData);
        FileWriter writer = new FileWriter(pluginYML);
        writer.append("# " + header.replace("\n", "\n# ") + "\n");
        writer.append(out.getStr(0));
        writer.close();
    }
}
