package nl.voidgroup.gradle.plugin.opengmph.task;

import nl.voidgroup.gradle.plugin.opengmph.Util;
import nl.voidgroup.gradle.plugin.opengmph.annotation.YML;
import nl.voidgroup.gradle.plugin.opengmph.data.YMLObject;
import nl.voidgroup.gradle.plugin.opengmph.data.minecraft.GenYMLHandler;
import nl.voidgroup.gradle.plugin.opengmph.data.minecraft.MinecraftServer;
import nl.voidgroup.gradle.plugin.opengmph.extension.PluginData;
import org.gradle.api.DefaultTask;
import org.gradle.api.tasks.TaskAction;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;

public class GenYML extends DefaultTask {

    private static final String header = "Generated by: <nl.voidgroup.opengmph@0.0.1-dev-002>";

    @TaskAction
    public void run() throws IOException, NoSuchMethodException, IllegalAccessException, InvocationTargetException, InstantiationException {
        PluginData data = getProject().getExtensions().getByType(PluginData.class);
        MinecraftServer targetServer = Util.requireNonNull(data.targetServer, "Target server not set");
        if(!targetServer.getClass().isAnnotationPresent(YML.class)) {
            getLogger().warn("Current target server does not support yml generating");
            return;
        }
        YML yml = targetServer.getClass().getAnnotation(YML.class);
        Class<? extends GenYMLHandler> handler = yml.handler();
        File pluginYML = new File(getProject().getBuildDir().getAbsoluteFile() + "/resources/" + yml.file());
        if(pluginYML.getParentFile().mkdirs()) {
            getLogger().info("Created parent dirs for yml");
        }
        if(pluginYML.createNewFile()) {
            getLogger().info("Created yml");
        }
        FileWriter writer = new FileWriter(pluginYML);
        YMLObject obj = handler.getConstructor().newInstance().run(data);
        writer.append("# ").append(header.replace("\n", "\n# ")).append("\n");
        writer.append(obj.getStr(0));
        writer.close();
    }

}
